### ISSUE TITLE
Router + bodyparser etc

### ISSUE THREAD

**Issue by ghost** [smrsan76/x-hexo-app-express#1]
Sorry for stupid question...

Can I use this plugin to make Express the main engine for my Hexo blog?

I want to use `router` and `bodyparser` etc to make API calls in my Hexo... can I use your app for that? How?

Sorry again, I am newbie.

**Comment by smrsan76** [comment]
Hi @rabas007 

> Can I use this plugin to make Express the main engine for my Hexo blog?

For a short answer, I should tell you "_Don't use this package for performance and some other issues !_"

This package renders all your blog's src and assets each time a user requests for visiting your static pages !
The best approach for this kinda usage is that render all your blog's src before deploying your blog.

e.g. Use the standard [hexo-cli](https://www.npmjs.com/package/hexo-cli) and [hexo-server](https://www.npmjs.com/package/hexo-server) packages for making your static content.
Then put them into a folder of your main app, and [serve them as static files](http://expressjs.com/en/starter/static-files.html) in a separate route using express.

Thanks for sharing this issue
